
console.log("Hello World!")

/*
    This is the boilerplate for nodejs with typescript, which is generated by Webpack.
    You could write your code here with needed dependencies and configurations. 
*/
